#!/usr/bin/env python3
"""Seed the database with papers found via web search."""

import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, SCRIPT_DIR)

from database import ResearchDatabase

PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
DB_PATH = os.path.join(PROJECT_ROOT, "docs", "research", "database.json")

WEB_PAPERS = [
    {
        "source": "web_search",
        "paper_id": "",
        "title": "How can basic research on spatial cognition enhance the visual accessibility of architecture for people with low vision?",
        "authors": ["Gordon E. Legge", "Jialiang Yu", "Bosco S. Tjan"],
        "year": 2021,
        "abstract": "Defines functional challenges in perception and spatial cognition with restricted visual information. Reviews empirical work on low vision perception of spaces and evaluates how results provide insights for architects designing visually accessible spaces.",
        "citation_count": 0,
        "venue": "Cognitive Research: Principles and Implications",
        "url": "https://link.springer.com/article/10.1186/s41235-020-00265-y",
        "doi": "10.1186/s41235-020-00265-y",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Architects and Visually Impaired People: Teaching Architecture with and for People Born Blind",
        "authors": ["Ann Heylighen", "Jasmien Herssens"],
        "year": 2014,
        "abstract": "Advances disability as a resource to complement designers' visual way of knowing. Shows architecture students are unaware of how common building materials feel and unable to identify them by touch.",
        "citation_count": 0,
        "venue": "International Journal of Architectural Research (Archnet-IJAR)",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Making Engineering Education Accessible to Blind and Low-Vision Learners",
        "authors": ["Cecilia Mauceri", "Anne H. Spencer"],
        "year": 2024,
        "abstract": "Details how the first blind student to enroll in an introductory electrical engineering course at Stanford navigated the class, identifying accessibility gaps and solutions. Won Best DEI Paper at the 2024 ASEE conference.",
        "citation_count": 0,
        "venue": "ASEE Annual Conference & Exposition",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Cognitive map formation in the blind is enhanced by three-dimensional tactile information",
        "authors": ["Corinna M. Bauer", "Gabriella V. Hirsch", "Lauren Engel", "Samantha Gebodh", "Lotfi B. Merabet"],
        "year": 2023,
        "abstract": "Compared equivalent 2D swell paper and 3D printed tactile maps. Early blind participants showed stronger cognitive map formation with 3D mazes. 3D maps produced with Prusa i3 MK2S printer; 2D maps with PIAF Tactile Image Maker.",
        "citation_count": 0,
        "venue": "Scientific Reports (Nature)",
        "url": "",
        "doi": "10.1038/s41598-023-36578-3",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Cognitive map formation through tactile map navigation in visually impaired and sighted persons",
        "authors": ["Jakub Budnik", "Anna Warchol-Celinska", "Anna Wasilewska"],
        "year": 2022,
        "abstract": "Investigates cognitive map formation via tactile map navigation, finding that after extensive training, persons with visual impairments and sighted persons form equally accurate mental representations of tactile map layouts.",
        "citation_count": 0,
        "venue": "Scientific Reports (Nature)",
        "url": "",
        "doi": "10.1038/s41598-022-15858-4",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "A Systematic Literature Review on the Automatic Creation of Tactile Graphics for the Blind and Visually Impaired",
        "authors": ["Mukhriddin Mukhiddinov", "Jinsoo Kim"],
        "year": 2021,
        "abstract": "Systematic review screening 250+ papers on automatic tactile graphic generation. Reviews thermoforming, swell paper, embossing, and special printers (PIAF, ViewPlus Tiger, Index Braille).",
        "citation_count": 0,
        "venue": "Processes (MDPI)",
        "url": "",
        "doi": "10.3390/pr9101726",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Automatic (Tactile) Map Generation -- A Systematic Literature Review",
        "authors": ["Jakub Wabinski", "Albina Moscicka"],
        "year": 2019,
        "abstract": "Reviews algorithms and models for map generalization and automatic tactile map generation. Screened 500+ studies; found no comprehensive automatic solution yet exists.",
        "citation_count": 0,
        "venue": "ISPRS International Journal of Geo-Information",
        "url": "",
        "doi": "10.3390/ijgi8070293",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Using Tactile Maps to Improve the Practical Spatial Knowledge of Adults who are Blind",
        "authors": ["M. A. Espinosa", "E. Ochaita"],
        "year": 1998,
        "abstract": "Evaluated effects of direct experience, cartographic representation, and verbal description on spatial knowledge of 30 blind adults. Found practical spatial knowledge was better when participants learned routes with a tactile map.",
        "citation_count": 0,
        "venue": "Journal of Visual Impairment & Blindness",
        "url": "",
        "doi": "10.1177/0145482X9809200512",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Spatial navigation by congenitally blind individuals",
        "authors": ["Daniel-Robert Chebat", "Shachar Maidenbaum", "Amir Amedi"],
        "year": 2015,
        "abstract": "Reviews advances in neuroscience regarding spatial navigation by blind and sighted people. Addresses lack of consensus on the extent to which locomotion and wayfinding depend on amodal spatial representations.",
        "citation_count": 0,
        "venue": "WIREs Cognitive Science",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Wayfinding in the blind: larger hippocampal volume and supranormal spatial navigation",
        "authors": ["Robert J. Fortin", "Patrice Voss", "Franco Bherer"],
        "year": 2008,
        "abstract": "Shows blind individuals possess superior navigational skills on route learning tasks compared to sighted controls, and demonstrates significant volume increase of the hippocampus in blind individuals.",
        "citation_count": 0,
        "venue": "Brain",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "AI, architecture, accessibility, and data justice -- ACADIA special issue",
        "authors": ["Dana Cupkova", "Andrew John Wit", "Matias del Campo", "Mollie Claypool"],
        "year": 2023,
        "abstract": "Explores the current status of AI and ML learning frameworks in design and probes new methods of creation relative to data access and data justice.",
        "citation_count": 0,
        "venue": "International Journal of Architectural Computing",
        "url": "",
        "doi": "10.1177/14780771231171939",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Bridging Pixels and Fabrication: Enhancing Accessibility in CNC Knitting for Architectural Design",
        "authors": ["Nikoletta Karastathi", "Shylaja Regunathan", "David Doria", "Thomas Walpole", "Marjan Colletti"],
        "year": 2024,
        "abstract": "Explores using Kniterate CNC knitting machine with Grasshopper plug-in to enhance accessibility for designers and architects. Won the Vanguard Award at ACADIA 2024.",
        "citation_count": 0,
        "venue": "ACADIA 2024: Designing Change",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "From Cluttered to Clear: Improving the Web Accessibility Design for Screen Reader Users in E-commerce With Generative AI",
        "authors": [],
        "year": 2025,
        "abstract": "Presents a GenAI-based browser extension for automated optimization of website structure and content for screen reader users.",
        "citation_count": 0,
        "venue": "arXiv",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Information Wayfinding of Screen Reader Users: Five Personas to Expand Conceptualizations of User Experiences",
        "authors": [],
        "year": 2025,
        "abstract": "Distills notable patterns of screen reader use and presents five archetypal personas of screen reader users to address the gap in disability personas for design.",
        "citation_count": 0,
        "venue": "PMC",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Rich Screen Reader Experiences for Accessible Data Visualization",
        "authors": ["Jonathan Zong", "Crystal Lee", "Alan Lundgard", "JiWoong Jang", "Daniel Hajas", "Arvind Satyanarayan"],
        "year": 2022,
        "abstract": "Identifies three design dimensions (structure, navigation, description) for screen-reader-accessible visualizations. Best Paper Honorable Mention at EuroVis.",
        "citation_count": 0,
        "venue": "Computer Graphics Forum (EuroVis)",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Chart Reader: Accessible Visualization Experiences Designed with Screen Reader Users",
        "authors": ["John R. Thompson", "Jesse Martinez", "Alper Sarikaya", "Edward Cutrell", "Bongshin Lee"],
        "year": 2023,
        "abstract": "Co-design study with 10 BLV screen reader users to develop accessible visualization experiences. Synthesizes hierarchical navigation, sonification, and cross-cutting insights.",
        "citation_count": 0,
        "venue": "CHI 2023",
        "url": "",
        "doi": "10.1145/3544548.3581186",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Understanding Screen-Reader Users' Experiences with Online Data Visualizations",
        "authors": ["Pramod Chundury", "Biswaksen Patnaik", "Yevgen Borodin", "IV Ramakrishnan"],
        "year": 2021,
        "abstract": "Found that BLV users spend 211% more time interacting with charts and are 61% less accurate in extracting information. 33% of visualizations were undiscoverable to screen readers.",
        "citation_count": 0,
        "venue": "ASSETS 2021 (ACM SIGACCESS)",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "The Impact of AI on Developer Productivity: Evidence from GitHub Copilot",
        "authors": ["Sida Peng", "Eirini Kalliamvakou", "Peter Cihon", "Mert Demirer"],
        "year": 2023,
        "abstract": "Controlled experiment where treatment group with AI pair programmer completed HTTP server implementation 55.8% faster. Developers with less experience benefited most.",
        "citation_count": 0,
        "venue": "arXiv (Microsoft Research)",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Who is Using AI to Code? Global Diffusion and Impact of Generative AI",
        "authors": [],
        "year": 2025,
        "abstract": "Applied neural classifier to 30M+ commits from 160,097 developers across six countries. By end of 2024, ~29% of Python functions had substantial AI support.",
        "citation_count": 0,
        "venue": "Science",
        "url": "",
        "doi": "10.1126/science.adz9311",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Inclusive Design Studios: Rethinking the Instructor's Role",
        "authors": [],
        "year": 2022,
        "abstract": "Drawing on research on expertise cultivation, student motivation, and stereotype threat, considers how to rethink design studio instruction to be more inclusive.",
        "citation_count": 0,
        "venue": "Enquiry: The ARCC Journal for Architectural Research",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "The emerging intersection: the role of architecture in promoting inclusive education",
        "authors": [],
        "year": 2024,
        "abstract": "Critically reviews literature published 2010-2022 on architecture's role in inclusive education. Argues universal design principles need to be applied for accessible architectural designs.",
        "citation_count": 0,
        "venue": "Oxford Review of Education",
        "url": "",
        "doi": "10.1080/03054985.2024.2427041",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Universal Design for Learning and Instruction: Effective Strategies for Inclusive Higher Education",
        "authors": [],
        "year": 2023,
        "abstract": "Universal Design originated in architecture by Ron Mace to promote accessible design. Explores how UDL and UDI emerge as teaching strategies encouraging inclusion in education.",
        "citation_count": 0,
        "venue": "Education Sciences (MDPI)",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Haptic design research: A blind sense of space",
        "authors": ["Jasmien Herssens", "Ann Heylighen"],
        "year": 2011,
        "abstract": "Develops haptic design parameters for architects based on classification of haptics into active, dynamic and passive touch. Parameters derived from expertise of people born blind.",
        "citation_count": 0,
        "venue": "International Association of Societies of Design Research (IASDR)",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Designing Architecture for More: A Framework of Haptic Design Parameters with the Experience of People Born Blind",
        "authors": ["Jasmien Herssens"],
        "year": 2011,
        "abstract": "Framework to support architects in paying attention to role of touch during design. Characteristics based on expertise of people born blind and professional caregivers.",
        "citation_count": 0,
        "venue": "PhD Dissertation, Hasselt University",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Towards Automatically Generated Tactile Detail Maps by 3D Printers for Blind Persons",
        "authors": ["Stefan Gotzelmann", "Aleksander Pavkovic"],
        "year": 2014,
        "abstract": "Introduces approach for semi-automatic generation of worldwide available detailed tactile maps including buildings and blind-specific features. Generates 2.1D tactile models printable by consumer 3D printers.",
        "citation_count": 0,
        "venue": "ICCHP 2014 (Springer)",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Interactive 3D Printed Urban Maps for Blind People",
        "authors": [],
        "year": 2023,
        "abstract": "Proposes haptic device allowing blind users to explore object locations on a 3D physical model with audio descriptions activated by tapping. Study with 11 blind participants received positive feedback.",
        "citation_count": 0,
        "venue": "ICCHP 2023 (Springer)",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Map Learning with a 3D Printed Interactive Small-Scale Model: Improvement of Space and Text Memorization in Visually Impaired Students",
        "authors": [],
        "year": 2017,
        "abstract": "Investigates 3D printed interactive small-scale models for map learning by visually impaired students. Addresses problem of working memory overload from back-and-forth between tactile drawing and braille legend.",
        "citation_count": 0,
        "venue": "Frontiers in Psychology",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "shapeCAD: An Accessible 3D Modelling Workflow for the Blind and Visually-Impaired Via 2.5D Shape Displays",
        "authors": ["Alexa F. Siu", "Son Kim", "Joshua A. Miele", "Sean Follmer"],
        "year": 2019,
        "abstract": "Co-designed with three blind users to create accessible 3D modelling using script-based CAD (OpenSCAD) and a 2.5D tactile pin shape display. Users can haptically explore, modify, and author new 3D models.",
        "citation_count": 0,
        "venue": "ASSETS 2019 (ACM SIGACCESS)",
        "url": "",
        "doi": "10.1145/3308561.3353782",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "A Practical CAD Method for the Visually Impaired: A Case of Modeling the Leaning Tower of Pisa",
        "authors": ["Kazunori Minatani"],
        "year": 2023,
        "abstract": "Author, who is totally blind, devised a form of programmable CAD modeling not requiring screen confirmation. Subjective evaluation confirmed models comparable to those by sighted users.",
        "citation_count": 0,
        "venue": "HCII 2023 (Springer)",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Enabling Uniform Computer Interaction Experience for Blind Users through Large Language Models",
        "authors": ["Vikas Ashok", "Ramakrishnan"],
        "year": 2024,
        "abstract": "Developed Savant, an LLM-powered assistive technology that allows blind screen reader users to interact uniformly with any application interface through natural language.",
        "citation_count": 0,
        "venue": "ASSETS 2024 (ACM SIGACCESS)",
        "url": "",
        "doi": "10.1145/3663548.3675605",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "The Impact of Generative AI Coding Assistants on Developers Who Are Visually Impaired",
        "authors": [],
        "year": 2025,
        "abstract": "Uses Activity Theory framework to examine how visually impaired developers interact with AI coding assistants. AI often exacerbated accessibility barriers, with users requesting AI timeouts.",
        "citation_count": 0,
        "venue": "CHI 2025",
        "url": "",
        "doi": "10.1145/3706598.3714008",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "I look at it as the king of knowledge: How Blind People Use and Understand Generative AI Tools",
        "authors": ["Maitraye Das"],
        "year": 2024,
        "abstract": "Rich empirical study of how blind people integrate GenAI tools to enhance productivity and access information in their regular work practices.",
        "citation_count": 0,
        "venue": "ASSETS 2024 (ACM SIGACCESS)",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "TactileNet: Bridging the Accessibility Gap with AI-Generated Tactile Graphics for Individuals with Vision Impairment",
        "authors": [],
        "year": 2025,
        "abstract": "AI-based approach that automates tactile graphic generation to accelerate production and democratize access to educational materials for visually impaired learners.",
        "citation_count": 0,
        "venue": "arXiv",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Universal design, inclusive design, accessible design, design for all: different concepts -- one goal?",
        "authors": ["Inger Marie Lid"],
        "year": 2014,
        "abstract": "Discusses UD as an interdisciplinary topic relevant for rehabilitation and building professions. Argues the UN CRPD pre-supposes a relational model of disability.",
        "citation_count": 0,
        "venue": "Universal Access in the Information Society",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Universal Design Research as a New Materialist Practice",
        "authors": [],
        "year": 2015,
        "abstract": "Returns to Universal Design as a design phenomenon, arguing that critical disability theory should understand UD research to formulate a nuanced, new materialist disability epistemology.",
        "citation_count": 0,
        "venue": "Disability Studies Quarterly",
        "url": "",
        "doi": "",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Guidelines for Standardizing the Design of Tactile Maps: A Review of Research and Best Practice",
        "authors": [],
        "year": 2022,
        "abstract": "Reviews research and best practices for standardizing the design of tactile maps for blind and visually impaired users.",
        "citation_count": 0,
        "venue": "The Cartographic Journal",
        "url": "",
        "doi": "10.1080/00087041.2022.2097760",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Chart4Blind: An Intelligent Interface for Chart Accessibility Conversion",
        "authors": [],
        "year": 2024,
        "abstract": "Intelligent user interface that converts bitmap image representations of line charts into universally accessible formats for BVI individuals.",
        "citation_count": 0,
        "venue": "IUI 2024 (ACM Intelligent User Interfaces)",
        "url": "",
        "doi": "10.1145/3640543.3645175",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Advancing Accessible 3D Design for the Blind and Visually-Impaired via Tactile Shape Displays",
        "authors": ["Alexa F. Siu"],
        "year": 2019,
        "abstract": "Explores tactile shape displays for making 3D design accessible to blind and visually-impaired users.",
        "citation_count": 0,
        "venue": "UIST 2019 Adjunct (ACM)",
        "url": "",
        "doi": "10.1145/3332167.3356875",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Enhancing universal design through co-design: perceptions of practice, process and outcomes",
        "authors": [],
        "year": 2026,
        "abstract": "Examines how co-design is implemented in the design of large-scale public buildings with people with disability. Argues for embedding co-design and universal design as intertwined, equity-driven practices.",
        "citation_count": 0,
        "venue": "Archnet-IJAR (Emerald Publishing)",
        "url": "",
        "doi": "10.1108/ARCH-08-2025-0340",
    },
    {
        "source": "web_search",
        "paper_id": "",
        "title": "Experimental study about 3D printed tactile symbols for tactile maps and blind users",
        "authors": [],
        "year": 2022,
        "abstract": "Experimental evaluation of 3D printed tactile symbols for use in tactile maps by blind users.",
        "citation_count": 0,
        "venue": "Journal of Accessibility and Design for All (JACCES)",
        "url": "",
        "doi": "",
    },
]


def main():
    db = ResearchDatabase(DB_PATH)
    added = db.add_entries(WEB_PAPERS)
    db.tag_entries({})
    db.save()
    print("OK: Added {} web-searched papers (total: {})".format(
        added, len(db.data["entries"])
    ))
    print("READY:")


if __name__ == "__main__":
    main()
